/* ==========================================================================
   Elitex Interior — public site runtime
   --------------------------------------------------------------------------
   Renders every page from content/content.json (the CMS database):
     • hydrates text sections in place (no layout shift)
     • renders media collections with skeletons + IntersectionObserver lazy load
     • applies Cloudinary transformations (f_auto/q_auto → WebP/AVIF)
     • applies SEO meta from the CMS
     • powers forms, modals, sliders, counters
     • live-preview bridge: instant re-render from the Admin Dashboard
   Pages declare themselves via <body data-page="home|showcase|showcase2|reviews">
   ========================================================================== */
(function () {
  'use strict';

  var PAGE = document.body.getAttribute('data-page') || 'home';
  var PREVIEW = /[?&]cmsPreview=1/.test(location.search);
  var DRAFT_KEY = 'elitexcms.draft.v1';
  var content = null;
  var swiperInstance = null;

  /* ------------------------------------------------------------------ */
  /* Helpers                                                             */
  /* ------------------------------------------------------------------ */

  function $(sel, root) { return (root || document).querySelector(sel); }
  function $$(sel, root) { return Array.prototype.slice.call((root || document).querySelectorAll(sel)); }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  /* escape, but allow explicit <br> line breaks stored in content */
  function escBr(s) { return esc(s).replace(/&lt;br\s*\/?&gt;/gi, '<br>'); }

  function setText(sel, value) {
    var el = $(sel);
    if (el && value != null) el.textContent = value;
  }
  function setHtml(sel, value) {
    var el = $(sel);
    if (el && value != null) el.innerHTML = value;
  }

  /* visible items: published always; drafts only in preview (with badge) */
  function items(list) {
    if (!Array.isArray(list)) return [];
    return list
      .filter(function (it) {
        if (!it || it.status === 'hidden') return false;
        if (it.status === 'draft') return PREVIEW;
        return true;
      })
      .sort(function (a, b) { return (a.order || 0) - (b.order || 0); });
  }
  function draftBadge(it) {
    return (PREVIEW && it.status === 'draft') ? '<span class="cms-draft-badge">Draft</span>' : '';
  }

  /* ------------------------------------------------------------------ */
  /* Cloudinary                                                          */
  /* ------------------------------------------------------------------ */

  var CLD_RE = /(https?:\/\/res\.cloudinary\.com\/[^/]+\/(image|video)\/upload\/)(.*)$/;

  function cldImage(url, width) {
    var m = CLD_RE.exec(url || '');
    if (!m || m[2] !== 'image') return url;
    if (/\/upload\/[a-z]+_[^/]*\//.test(url)) return url; // already transformed
    return m[1] + 'f_auto,q_auto,c_limit,w_' + (width || 1000) + '/' + m[3];
  }
  function cldVideo(url) {
    var m = CLD_RE.exec(url || '');
    if (!m || m[2] !== 'video') return url;
    if (/\/upload\/[a-z]+_[^/]*\//.test(url)) return url;
    return m[1] + 'q_auto/' + m[3];
  }
  /* poster frame generated by Cloudinary from the first video frame */
  function cldPoster(url, width) {
    var m = CLD_RE.exec(url || '');
    if (!m || m[2] !== 'video') return '';
    var rest = m[3].replace(/\.(mp4|mov|webm)(\?.*)?$/i, '.jpg');
    return m[1] + 'so_0,f_auto,q_auto,c_limit,w_' + (width || 800) + '/' + rest;
  }

  /* ------------------------------------------------------------------ */
  /* Lazy loading                                                        */
  /* ------------------------------------------------------------------ */

  var io = ('IntersectionObserver' in window) ? new IntersectionObserver(function (entries) {
    entries.forEach(function (entry) {
      var el = entry.target;
      if (el.tagName === 'VIDEO') {
        var src = el.querySelector('source');
        if (entry.isIntersecting) {
          if (src && !src.src && src.getAttribute('data-src')) {
            src.src = src.getAttribute('data-src');
            el.load();
            el.addEventListener('loadeddata', function () {
              var wrap = el.closest('.lazy-media'); if (wrap) wrap.classList.add('is-loaded');
            }, { once: true });
          }
          var p = el.play(); if (p && p.catch) p.catch(function () {});
        } else if (!el.paused) {
          el.pause();
        }
      } else if (el.tagName === 'IMG') {
        if (entry.isIntersecting) {
          if (!el.src && el.getAttribute('data-src')) {
            el.src = el.getAttribute('data-src');
            el.addEventListener('load', function () {
              var wrap = el.closest('.lazy-media'); if (wrap) wrap.classList.add('is-loaded');
            }, { once: true });
          }
          io.unobserve(el);
        }
      }
    });
  }, { rootMargin: '200px 0px', threshold: 0.05 }) : null;

  function observeLazy(root) {
    $$('video[data-lazy], img[data-src]', root).forEach(function (el) {
      if (io) { io.observe(el); }
      else if (el.tagName === 'IMG') { el.src = el.getAttribute('data-src'); }
      else {
        var s = el.querySelector('source');
        if (s && s.getAttribute('data-src')) { s.src = s.getAttribute('data-src'); el.load(); el.play(); }
      }
    });
  }

  function videoTag(src, opts) {
    opts = opts || {};
    var poster = cldPoster(src, opts.posterWidth || 800);
    return '<video muted playsinline loop preload="none" data-lazy="1"' +
      (poster ? ' poster="' + esc(poster) + '"' : '') +
      ' class="' + esc(opts.className || 'w-full h-full object-cover') + '">' +
      '<source data-src="' + esc(cldVideo(src)) + '" type="video/mp4"></video>';
  }
  function imgTag(src, alt, opts) {
    opts = opts || {};
    return '<img data-src="' + esc(cldImage(src, opts.width || 1000)) + '" alt="' + esc(alt || '') + '"' +
      ' loading="lazy" decoding="async" class="' + esc(opts.className || 'w-full h-full object-cover') + '">';
  }

  /* ------------------------------------------------------------------ */
  /* SEO                                                                 */
  /* ------------------------------------------------------------------ */

  var SEO_PAGE_KEY = { home: 'index', showcase: 'project', showcase2: 'project2', reviews: 'reviews' };

  function metaSet(attrName, attrValue, contentValue) {
    if (contentValue == null || contentValue === '') return;
    var el = document.head.querySelector('meta[' + attrName + '="' + attrValue + '"]');
    if (!el) {
      el = document.createElement('meta');
      el.setAttribute(attrName, attrValue);
      document.head.appendChild(el);
    }
    el.setAttribute('content', contentValue);
  }
  function linkSet(rel, href) {
    if (!href) return;
    var el = document.head.querySelector('link[rel="' + rel + '"]');
    if (!el) { el = document.createElement('link'); el.setAttribute('rel', rel); document.head.appendChild(el); }
    el.setAttribute('href', href);
  }

  function applySeo() {
    var seo = content.seo || {};
    var page = (seo.pages || {})[SEO_PAGE_KEY[PAGE]] || {};
    if (page.title) document.title = page.title;
    metaSet('name', 'description', page.description);
    metaSet('name', 'keywords', page.keywords);
    metaSet('name', 'robots', page.robots);
    metaSet('property', 'og:title', page.ogTitle || page.title);
    metaSet('property', 'og:description', page.ogDescription || page.description);
    metaSet('property', 'og:image', page.ogImage);
    metaSet('property', 'og:url', page.canonical);
    metaSet('property', 'twitter:title', page.ogTitle || page.title);
    metaSet('property', 'twitter:description', page.ogDescription || page.description);
    metaSet('property', 'twitter:image', page.ogImage);
    if (page.canonical) linkSet('canonical', page.canonical);
    if (seo.faviconUrl) linkSet('icon', seo.faviconUrl);

    var sd = seo.structuredData || {};
    if (sd.enabled) {
      var contact = (content.site || {}).contact || {};
      var json = {
        '@context': 'https://schema.org',
        '@type': sd.type || 'LocalBusiness',
        name: sd.name || content.site.name,
        description: sd.description || '',
        url: (content.site || {}).domain || location.origin,
        telephone: contact.phone || undefined,
        address: contact.address ? { '@type': 'PostalAddress', streetAddress: contact.address, addressLocality: 'Abuja', addressCountry: 'NG' } : undefined,
        priceRange: sd.priceRange || undefined,
        areaServed: sd.areaServed || undefined
      };
      var el = document.getElementById('cms-jsonld');
      if (!el) {
        el = document.createElement('script');
        el.type = 'application/ld+json';
        el.id = 'cms-jsonld';
        document.head.appendChild(el);
      }
      el.textContent = JSON.stringify(json);
    }
  }

  /* ------------------------------------------------------------------ */
  /* Shared renderers                                                    */
  /* ------------------------------------------------------------------ */

  function whatsappUrl() {
    var c = content.site.contact;
    return 'https://wa.me/' + (c.whatsappNumber || '') + '?text=' + encodeURIComponent(c.whatsappMessage || '');
  }

  function renderFooterCommon() {
    var f = content.pages.home.footer;
    setText('[data-cms="footer-brand"]', f.brandName);
    setText('[data-cms="footer-blurb"]', f.blurb);
    setText('[data-cms="footer-copy"]', '\u00A9 ' + new Date().getFullYear() + ' ' + f.copyright);

    var social = $('[data-cms="footer-social"]');
    if (social) {
      social.innerHTML = items(content.site.social).map(function (s) {
        return '<a href="' + esc(s.url) + '" target="_blank" rel="noopener" aria-label="' + esc(s.platform) + '"' +
          ' class="text-2xl hover:text-[var(--secondary)] transition-colors"><i class="' + esc(s.icon) + '"></i></a>';
      }).join('');
    }
  }

  /* ------------------------------------------------------------------ */
  /* HOME page                                                           */
  /* ------------------------------------------------------------------ */

  function renderHome() {
    var p = content.pages.home;

    /* nav */
    setText('[data-cms="nav-logo"]', p.nav.logoText);
    var navLinks = items(p.nav.links).map(function (l) {
      return '<a href="' + esc(l.href) + '" class="hover:text-[var(--secondary)] transition-colors">' + esc(l.label) + '</a>';
    }).join('');
    setHtml('[data-cms="nav-links"]', navLinks);
    var navCta = $('[data-cms="nav-cta"]');
    if (navCta) { navCta.textContent = p.nav.cta.label; navCta.href = p.nav.cta.href; }
    var mob = $('[data-cms="mobile-links"]');
    if (mob) {
      mob.innerHTML = items(p.nav.links).map(function (l) {
        return '<a href="' + esc(l.href) + '" class="mobile-menu-link hover:text-[var(--secondary)] transition-colors">' + esc(l.label) + '</a>';
      }).join('') +
      '<a href="' + esc(p.nav.cta.href) + '" class="mobile-menu-link mt-8 inline-block px-6 py-3 rounded-xl bg-[var(--secondary)] text-[var(--primary)] text-base font-bold hover:bg-[#B89A5D] transition-colors">' + esc(p.nav.cta.label) + '</a>';
    }

    /* hero */
    setText('[data-cms="hero-title"]', p.hero.title);
    var tag = $('[data-cms="hero-tagline"]');
    if (tag) {
      tag.innerHTML = esc(p.hero.taglinePrefix) +
        '<span class="font-bold text-white" style="background: linear-gradient(135deg, #C9A96E 0%, #E8D9B5 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;">' +
        esc(p.hero.taglineHighlight) + '</span>';
    }
    setText('[data-cms="hero-subtitle"]', p.hero.subtitle);
    setText('[data-cms="hero-scroll-hint"]', p.hero.scrollHint);
    var cs = $('[data-cms="hero-cta-secondary"]');
    if (cs) { cs.href = p.hero.ctaSecondary.href; cs.firstChild.textContent = p.hero.ctaSecondary.label + ' '; }
    var cp = $('[data-cms="hero-cta-primary"]');
    if (cp) { cp.href = p.hero.ctaPrimary.href; cp.textContent = p.hero.ctaPrimary.label; }

    /* about */
    var about = $('#about');
    if (about) about.style.display = p.about.visible === false ? 'none' : '';
    setText('[data-cms="about-heading"]', p.about.heading);
    setText('[data-cms="about-p1"]', p.about.paragraphs[0] || '');
    setText('[data-cms="about-p2"]', p.about.paragraphs[1] || '');
    var aboutCta = $('[data-cms="about-cta"]');
    if (aboutCta) {
      aboutCta.href = p.about.cta.href;
      aboutCta.innerHTML = esc(p.about.cta.label) + ' <i class="fas fa-users"></i>';
    }
    var aboutVideo = $('[data-cms="about-video"]');
    if (aboutVideo) {
      var srcNow = aboutVideo.getAttribute('src');
      var want = p.about.videoSrc;
      if (srcNow !== want) aboutVideo.setAttribute('src', /res\.cloudinary/.test(want) ? cldVideo(want) : want);
    }

    /* services */
    var svc = $('#services'); if (svc) svc.style.display = p.services.visible === false ? 'none' : '';
    setText('[data-cms="services-heading"]', p.services.heading);
    setText('[data-cms="services-subtitle"]', p.services.subtitle);
    setHtml('#servicesGrid', items(p.services.items).map(function (s) {
      return '<div class="fade-in text-center p-8 rounded-3xl bg-white border border-gray-200 shadow-lg hover:shadow-2xl hover:-translate-y-2 transition-all duration-300 relative">' + draftBadge(s) +
        '<div class="w-20 h-20 rounded-full bg-[var(--secondary)]/10 flex items-center justify-center mx-auto mb-6 text-4xl text-[var(--secondary)]"><i class="' + esc(s.icon) + '"></i></div>' +
        '<h3 class="text-2xl font-bold mb-4">' + esc(s.title) + '</h3>' +
        '<p class="text-gray-700">' + esc(s.description) + '</p></div>';
    }).join(''));

    /* portfolio */
    var pf = $('#portfolio'); if (pf) pf.style.display = p.portfolio.visible === false ? 'none' : '';
    setText('[data-cms="portfolio-heading"]', p.portfolio.heading);
    setText('[data-cms="portfolio-subtitle"]', p.portfolio.subtitle);
    var grid = $('#portfolioGrid');
    if (grid) {
      grid.innerHTML = items(p.portfolio.items).map(function (it) {
        var sizeCls = it.size && it.size !== 'normal' ? ' ' + it.size : '';
        var media = it.mediaType === 'video' ? videoTag(it.src) : imgTag(it.src, it.alt || it.title, { width: 900 });
        var overlay = '<div class="content-overlay">' +
          (it.title ? '<h3 class="text-xl font-semibold">' + esc(it.title) + '</h3>' : '') +
          (it.subtitle ? '<p class="text-white/80 text-sm">' + esc(it.subtitle) + '</p>' : '') + '</div>';
        var play = it.mediaType === 'video' ? '<div class="video-play-btn"><i class="fas fa-play"></i></div>' : '';
        var dataVideo = it.mediaType === 'video' ? ' data-video-src="' + esc(cldVideo(it.modalVideoSrc || it.src)) + '"' : '';
        return '<div class="grid-item' + sizeCls + ' fade-in lazy-media"' + dataVideo + '>' + draftBadge(it) + media + overlay + play + '</div>';
      }).join('');
      observeLazy(grid);
      bindVideoModal(grid);
    }
    var viewAll = $('#portfolioViewAll');
    if (viewAll) {
      viewAll.href = p.portfolio.viewAll.href;
      viewAll.firstChild.textContent = ' ' + p.portfolio.viewAll.label + ' ';
    }

    /* process */
    var pr = $('#process'); if (pr) pr.style.display = p.process.visible === false ? 'none' : '';
    setText('[data-cms="process-heading"]', p.process.heading);
    setText('[data-cms="process-subtitle"]', p.process.subtitle);
    setHtml('#processGrid', items(p.process.steps).map(function (s, i) {
      return '<div class="fade-in text-center p-8 rounded-3xl bg-white border border-gray-200 shadow-lg hover:shadow-xl transition-shadow relative">' + draftBadge(s) +
        '<div class="w-16 h-16 rounded-2xl bg-[#C9A96E]/10 flex items-center justify-center mx-auto mb-6"><span class="text-2xl font-black text-[#C9A96E]">' + (i + 1) + '</span></div>' +
        '<h3 class="text-xl font-bold mb-4">' + esc(s.title) + '</h3>' +
        '<p class="text-gray-700">' + esc(s.description) + '</p></div>';
    }).join(''));

    /* testimonials */
    var ts = $('#testimonials'); if (ts) ts.style.display = p.testimonials.visible === false ? 'none' : '';
    setText('[data-cms="testimonials-heading"]', p.testimonials.heading);
    setText('[data-cms="testimonials-subtitle"]', p.testimonials.subtitle);
    var wrap = $('#testimonialWrapper');
    if (wrap) {
      wrap.innerHTML = items(p.testimonials.slides).map(function (t) {
        return '<div class="swiper-slide bg-gray-50 rounded-2xl p-8 border border-gray-200 relative">' + draftBadge(t) +
          '<div class="flex items-center mb-4">' +
          '<img class="w-16 h-16 rounded-full object-cover mr-4" loading="lazy" src="' + esc(cldImage(t.avatar, 200)) + '" alt="' + esc(t.name) + '">' +
          '<div><h4 class="font-bold text-lg">' + esc(t.name) + '</h4>' +
          '<p class="text-sm text-gray-500">' + esc(t.location) + '</p></div></div>' +
          '<p class="text-gray-700 italic">"' + esc(t.quote) + '"</p></div>';
      }).join('');
      initSwiper();
    }

    /* reviews CTA */
    var rc = $('#reviews-showcase'); if (rc) rc.style.display = p.reviewsCta.visible === false ? 'none' : '';
    setText('[data-cms="reviewscta-heading"]', p.reviewsCta.heading);
    setText('[data-cms="reviewscta-subtitle"]', p.reviewsCta.subtitle);
    setHtml('#statsGrid', items(content.site.stats).map(function (s) {
      return '<div class="text-center p-6 rounded-2xl bg-white/5 backdrop-blur-sm border border-white/10 hover:border-[var(--secondary)] transition-all duration-300 fade-in relative">' + draftBadge(s) +
        '<div class="text-3xl md:text-4xl font-bold text-[var(--secondary)] mb-2">' + esc(s.value) + esc(s.suffix) + '</div>' +
        '<div class="text-gray-300 text-sm md:text-base">' + esc(s.label) + '</div></div>';
    }).join(''));
    var ctaLink = $('[data-cms="reviewscta-link"]');
    if (ctaLink) {
      ctaLink.href = p.reviewsCta.cta.href;
      var span = ctaLink.querySelector('span'); if (span) span.textContent = p.reviewsCta.cta.label;
    }
    setHtml('#badgesRow', items(p.reviewsCta.badges).map(function (b) {
      return '<div class="flex items-center gap-2"><i class="' + esc(b.icon) + ' text-[var(--secondary)]"></i><span>' + esc(b.label) + '</span></div>';
    }).join(''));

    /* contact */
    var ct = $('#contact'); if (ct) ct.style.display = p.contactSection.visible === false ? 'none' : '';
    setText('[data-cms="contact-heading"]', p.contactSection.heading);
    setText('[data-cms="contact-subtitle"]', p.contactSection.subtitle);
    setText('[data-cms="contact-address-label"]', p.contactSection.addressLabel);
    setText('[data-cms="contact-address"]', content.site.contact.address);
    setText('[data-cms="contact-phone-label"]', p.contactSection.phoneLabel);
    setText('[data-cms="contact-phone"]', content.site.contact.phone);
    var map = $('#contactMap');
    if (map && map.src !== content.site.contact.mapEmbedSrc) map.src = content.site.contact.mapEmbedSrc;
    var form = $('#contact-form');
    if (form) {
      form.action = content.site.integrations.formspreeContact;
      var sel = form.querySelector('select[name="project"]');
      if (sel) {
        sel.innerHTML = '<option value="">Select project type</option>' + items(p.contactSection.form.projectTypes).map(function (o) {
          return '<option value="' + esc(o.value) + '">' + esc(o.label) + '</option>';
        }).join('');
      }
      var btn = form.querySelector('button[type="submit"]');
      if (btn) btn.textContent = p.contactSection.form.submitLabel;
    }

    /* footer */
    renderFooterCommon();
    setHtml('#footer-quicklinks', items(p.footer.quickLinks).map(function (l) {
      return '<li><a href="' + esc(l.href) + '" class="hover:text-[var(--secondary)] transition-colors">' + esc(l.label) + '</a></li>';
    }).join(''));
    setText('[data-cms="newsletter-title"]', p.footer.newsletter.title);
    setText('[data-cms="newsletter-text"]', p.footer.newsletter.text);
    var nf = $('#newsletter-form');
    if (nf) {
      nf.action = content.site.integrations.formspreeNewsletter;
      var inp = nf.querySelector('input[name="email"]');
      if (inp) inp.placeholder = p.footer.newsletter.placeholder;
      nf.style.display = p.footer.newsletter.visible === false ? 'none' : '';
    }

    initGsapFades();
  }

  function initSwiper() {
    if (typeof Swiper === 'undefined') return;
    if (swiperInstance) { try { swiperInstance.destroy(true, true); } catch (e) {} }
    swiperInstance = new Swiper('.testimonial-slider', {
      loop: true,
      autoplay: { delay: 5000, disableOnInteraction: false },
      pagination: { el: '.swiper-pagination', clickable: true },
      navigation: { nextEl: '.swiper-button-next', prevEl: '.swiper-button-prev' },
      breakpoints: {
        640: { slidesPerView: 1, spaceBetween: 20 },
        768: { slidesPerView: 2, spaceBetween: 30 },
        1024: { slidesPerView: 2, spaceBetween: 40 }
      }
    });
  }

  function bindVideoModal(grid) {
    var videoModal = $('#videoModal');
    var modalVideo = $('#modalVideo');
    if (!videoModal || !modalVideo) return;
    $$('.grid-item[data-video-src]', grid).forEach(function (item) {
      item.addEventListener('click', function () {
        modalVideo.src = item.getAttribute('data-video-src');
        videoModal.classList.add('active');
      });
    });
  }

  /* ------------------------------------------------------------------ */
  /* SHOWCASE pages (project.html / project2.html)                       */
  /* ------------------------------------------------------------------ */

  function renderShowcase() {
    var p = content.pages[PAGE]; /* showcase | showcase2 */

    setHtml('[data-cms="show-hero-title"]', escBr(p.hero.title));
    setText('[data-cms="show-hero-subtitle"]', p.hero.subtitle);
    setText('[data-cms="show-cta-primary"]', p.hero.ctaPrimary);
    setText('[data-cms="show-cta-secondary"]', p.hero.ctaSecondary);
    setText('[data-cms="show-grid-heading"]', p.gridHeading);
    setText('[data-cms="philosophy-heading"]', p.philosophy.heading);
    setText('[data-cms="philosophy-text"]', p.philosophy.text);
    var phil = $('[data-cms="philosophy-section"]');
    if (phil) phil.style.display = p.philosophy.visible === false ? 'none' : '';

    var audio = $('#cosmicAudio');
    var musicBtn = $('#toggleMusic');
    if (audio) {
      var src = audio.querySelector('source');
      if (src && p.audio.src && src.getAttribute('src') !== p.audio.src) src.setAttribute('src', p.audio.src);
    }
    if (musicBtn) musicBtn.style.display = (p.audio.enabled === false) ? 'none' : '';

    var grid = $('#showcaseGrid');
    if (grid) {
      grid.innerHTML = items(p.items).map(function (it) {
        var media = it.mediaType === 'video'
          ? '<video class="eternal-media" muted playsinline loop preload="none" data-lazy="1"' +
            (cldPoster(it.src, 700) ? ' poster="' + esc(cldPoster(it.src, 700)) + '"' : '') + '>' +
            '<source data-src="' + esc(cldVideo(it.src)) + '" type="video/mp4"></video>'
          : '<img data-src="' + esc(cldImage(it.src, 900)) + '" alt="' + esc(it.alt || it.title) + '" loading="lazy" decoding="async" class="eternal-media">';
        var overlay = (it.title || it.subtitle)
          ? '<div class="eternal-overlay">' +
            (it.title ? '<h3 class="text-2xl font-bold mb-2">' + esc(it.title) + '</h3>' : '') +
            (it.subtitle ? '<p class="text-gray-300">' + esc(it.subtitle) + '</p>' : '') + '</div>'
          : '';
        return '<div class="eternal-item lazy-media" data-category="' + esc(it.category) + '"' +
          (it.projectSlug ? ' data-project="' + esc(it.projectSlug) + '"' : '') + '>' +
          draftBadge(it) + media + overlay + '</div>';
      }).join('');
      observeLazy(grid);
      bindProjectModal(grid, p.details);
      initShowcaseItemAnimations();
    }
  }

  function bindProjectModal(root, details) {
    var modal = $('#projectModal');
    if (!modal) return;
    var modalVideo = $('#modalVideo');
    var modalImage = $('#modalImage');

    $$('[data-project]', root).forEach(function (item) {
      item.addEventListener('click', function () {
        var d = (details || {})[item.getAttribute('data-project')];
        if (!d) return;
        setText('#modalTitle', d.title || '');
        setText('#modalDescription', d.description || '');
        setText('#modalScale', d.scale || '');
        setText('#modalDate', d.date || '');
        setText('#modalLocation', d.location || '');
        setText('#modalPhilosophy', d.philosophy || '');
        if (d.video) {
          modalVideo.src = cldVideo(d.video);
          modalVideo.style.display = 'block';
          if (modalImage) modalImage.style.display = 'none';
          var pl = modalVideo.play(); if (pl && pl.catch) pl.catch(function () {});
        } else if (d.image) {
          if (modalImage) { modalImage.src = cldImage(d.image, 1200); modalImage.style.display = 'block'; }
          modalVideo.style.display = 'none';
        }
        modal.classList.add('active');
        document.body.style.overflow = 'hidden';
      });
    });

    var close = function () {
      modal.classList.remove('active');
      document.body.style.overflow = '';
      if (modalVideo) { modalVideo.pause(); modalVideo.removeAttribute('src'); modalVideo.load(); }
    };
    var closeBtn = $('#modalClose');
    if (closeBtn && !closeBtn.__bound) { closeBtn.__bound = true; closeBtn.addEventListener('click', close); }
    if (!modal.__bound) {
      modal.__bound = true;
      modal.addEventListener('click', function (e) { if (e.target === modal) close(); });
      document.addEventListener('keydown', function (e) { if (e.key === 'Escape') close(); });
    }
  }

  function initShowcaseItemAnimations() {
    if (typeof gsap === 'undefined' || typeof ScrollTrigger === 'undefined') return;
    gsap.utils.toArray('.eternal-item').forEach(function (item, i) {
      gsap.fromTo(item, { opacity: 0, y: 60 }, {
        opacity: 1, y: 0, duration: 0.8, delay: (i % 6) * 0.06,
        scrollTrigger: { trigger: item, start: 'top 85%', toggleActions: 'play none none none' }
      });
    });
  }

  /* ------------------------------------------------------------------ */
  /* REVIEWS page                                                        */
  /* ------------------------------------------------------------------ */

  function renderReviews() {
    var p = content.pages.reviews;

    var heroTitle = $('[data-cms="rev-hero-title"]');
    if (heroTitle) {
      heroTitle.innerHTML = esc(p.hero.titlePrefix) +
        '<span style="background: var(--eternal-gold); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;">' +
        esc(p.hero.titleHighlight) + '</span>';
    }
    setText('[data-cms="rev-hero-subtitle"]', p.hero.subtitle);

    setHtml('[data-cms="rev-stats"]', items(p.stats).map(function (s, i) {
      return '<div class="stat-card floating-element" style="animation-delay: ' + (0.2 * (i + 1)).toFixed(1) + 's;">' +
        '<div class="stat-number" data-target="' + esc(s.target) + '">0' + esc(s.suffix) + '</div>' +
        '<div class="stat-label">' + esc(s.label) + '</div></div>';
    }).join(''));

    setText('[data-cms="rev-cards-heading"]', p.cardsHeading);
    setText('[data-cms="rev-cards-subtitle"]', p.cardsSubtitle);
    var grid = $('[data-cms="rev-cards"]');
    if (grid) {
      grid.innerHTML = items(p.cards).map(function (c) {
        var stars = '';
        for (var i = 0; i < 5; i++) {
          stars += '<span class="star' + (i < (c.rating || 5) ? ' filled' : '') + '"><i class="fas fa-star"></i></span>';
        }
        var meta = [c.position, c.company].filter(Boolean).join(', ');
        return '<div class="review-card floating-element relative"' + (c.projectSlug ? ' data-project-slug="' + esc(c.projectSlug) + '"' : '') + '>' + draftBadge(c) +
          '<div class="review-header">' +
          '<img src="' + esc(cldImage(c.avatar, 200)) + '" alt="' + esc(c.name) + '" loading="lazy" class="client-avatar">' +
          '<div class="client-info"><h3>' + esc(c.name) + '</h3><p>' + esc(meta || c.location) + '</p></div></div>' +
          '<div class="rating">' + stars + '</div>' +
          '<p class="review-text">' + esc(c.text) + '</p>' +
          (c.showViewProject && c.projectSlug
            ? '<a href="#" class="project-link view-project-btn" data-project="' + esc(c.projectSlug) + '" onclick="return false;">View Project <i class="fas fa-arrow-right ml-2"></i></a>'
            : '') +
          '</div>';
      }).join('');
      bindProjectModal(grid, p.details);
    }

    setText('[data-cms="rev-video-heading"]', p.videoHeading);
    setText('[data-cms="rev-video-subtitle"]', p.videoSubtitle);
    var vids = $('[data-cms="rev-videos"]');
    if (vids) {
      vids.innerHTML = items(p.videoTestimonials).map(function (v) {
        return '<div class="video-testimonial floating-element lazy-media" data-video="' + esc(cldVideo(v.src)) + '">' + draftBadge(v) +
          '<video muted playsinline loop preload="none" data-lazy="1"' +
          (cldPoster(v.src, 700) ? ' poster="' + esc(cldPoster(v.src, 700)) + '"' : '') + '>' +
          '<source data-src="' + esc(cldVideo(v.src)) + '" type="video/mp4"></video>' +
          '<div class="video-overlay"><h3 class="text-lg font-bold">' + esc(v.title) + '</h3>' +
          '<p class="text-gray-300 text-sm">' + esc(v.subtitle) + '</p></div>' +
          '<div class="play-btn"><i class="fas fa-play"></i></div></div>';
      }).join('');
      observeLazy(vids);
      bindVideoTestimonials(vids);
    }

    setText('[data-cms="rev-form-heading"]', p.submitForm.heading);
    setText('[data-cms="rev-form-subtitle"]', p.submitForm.subtitle);
    var form = $('#review-form');
    if (form) form.action = content.site.integrations.formspreeReview;
    var sec = $('#submit-review');
    if (sec) sec.style.display = p.submitForm.visible === false ? 'none' : '';

    /* footer */
    renderFooterCommon();
    setText('[data-cms="footer-address"]', content.site.contact.address);
    setText('[data-cms="footer-phone"]', content.site.contact.phone);
    var ql = $('#footer-quicklinks');
    if (ql) {
      ql.innerHTML = [
        { label: 'About Us', href: 'index.html#about' },
        { label: 'Services', href: 'index.html#services' },
        { label: 'Portfolio', href: 'project.html' },
        { label: 'Contact', href: 'index.html#contact' },
        { label: 'Write Review', href: '#submit-review' }
      ].map(function (l) {
        return '<li><a href="' + esc(l.href) + '" class="hover:text-[var(--secondary)] transition-colors text-sm md:text-base">' + esc(l.label) + '</a></li>';
      }).join('');
    }

    initCounters();
    initReviewAnimations();
  }

  function bindVideoTestimonials(root) {
    var modal = $('#projectModal');
    var modalVideo = $('#modalVideo');
    var modalImage = $('#modalImage');
    if (!modal || !modalVideo) return;
    $$('.video-testimonial', root).forEach(function (v) {
      v.addEventListener('click', function () {
        modalVideo.src = v.getAttribute('data-video');
        modalVideo.style.display = 'block';
        if (modalImage) modalImage.style.display = 'none';
        setText('#modalTitle', (v.querySelector('.video-overlay h3') || {}).textContent || '');
        setText('#modalDescription', (v.querySelector('.video-overlay p') || {}).textContent || '');
        setText('#modalScale', 'Video Testimonial');
        setText('#modalDate', 'Recent Project');
        setText('#modalLocation', 'Abuja, Nigeria');
        setText('#modalPhilosophy', 'This testimonial captures the authentic experience of our client, showcasing the transformative power of our design philosophy in their own words.');
        modal.classList.add('active');
        var pl = modalVideo.play(); if (pl && pl.catch) pl.catch(function () {});
      });
    });
  }

  function initCounters() {
    if (typeof gsap === 'undefined' || typeof ScrollTrigger === 'undefined') return;
    $$('.stat-number').forEach(function (counter) {
      var target = parseFloat(counter.getAttribute('data-target'));
      var suffix = counter.textContent.replace(/[0-9.]/g, '');
      ScrollTrigger.create({
        trigger: counter,
        start: 'top 85%',
        once: true,
        onEnter: function () {
          var start = 0;
          var step = target / 60;
          var tick = function () {
            start += step;
            if (start < target) {
              counter.textContent = (target % 1 !== 0 ? start.toFixed(1) : Math.ceil(start)) + suffix;
              requestAnimationFrame(tick);
            } else {
              counter.textContent = (target % 1 !== 0 ? target.toFixed(1) : target) + suffix;
            }
          };
          tick();
        }
      });
    });
  }

  function initReviewAnimations() {
    if (typeof gsap === 'undefined' || typeof ScrollTrigger === 'undefined') return;
    gsap.utils.toArray('.review-card, .video-testimonial, .stat-card').forEach(function (item, i) {
      gsap.fromTo(item, { opacity: 0, y: 50 }, {
        opacity: 1, y: 0, duration: 0.8, delay: (i % 4) * 0.1,
        scrollTrigger: { trigger: item, start: 'top 85%', toggleActions: 'play none none none' }
      });
    });
  }

  /* ------------------------------------------------------------------ */
  /* Shared behaviours                                                   */
  /* ------------------------------------------------------------------ */

  function initGsapFades() {
    if (typeof gsap === 'undefined' || typeof ScrollTrigger === 'undefined') {
      $$('.fade-in').forEach(function (el) { el.classList.add('is-visible'); el.style.opacity = 1; el.style.transform = 'none'; });
      return;
    }
    gsap.registerPlugin(ScrollTrigger);
    $$('.fade-in').forEach(function (el) {
      gsap.fromTo(el, { opacity: 0, y: 50 }, {
        opacity: 1, y: 0, duration: 1,
        scrollTrigger: { trigger: el, start: 'top 85%', toggleActions: 'play none none none' }
      });
    });
  }

  function initHomeChrome() {
    var navbar = $('#navbar');
    if (navbar) {
      window.addEventListener('scroll', function () {
        navbar.style.background = window.scrollY > 50 ? 'rgba(10, 15, 26, 0.7)' : 'rgba(255, 255, 255, 0.05)';
      }, { passive: true });
    }
    var menuBtn = $('#menu-btn');
    var closeBtn = $('#close-menu-btn');
    var mobileMenu = $('#mobile-menu');
    if (menuBtn && mobileMenu) {
      menuBtn.addEventListener('click', function () { mobileMenu.classList.add('open'); });
      if (closeBtn) closeBtn.addEventListener('click', function () { mobileMenu.classList.remove('open'); });
      mobileMenu.addEventListener('click', function (e) {
        if (e.target.closest('.mobile-menu-link')) mobileMenu.classList.remove('open');
      });
    }
    var videoModal = $('#videoModal');
    var modalVideo = $('#modalVideo');
    var closeVideoModal = $('#closeVideoModal');
    if (videoModal && modalVideo) {
      var close = function () { videoModal.classList.remove('active'); modalVideo.pause(); modalVideo.removeAttribute('src'); modalVideo.load(); };
      if (closeVideoModal) closeVideoModal.addEventListener('click', close);
      videoModal.addEventListener('click', function (e) { if (e.target === videoModal) close(); });
      document.addEventListener('keydown', function (e) { if (e.key === 'Escape') close(); });
    }
  }

  function initShowcaseChrome() {
    /* custom cursor (desktop only) */
    var cursor = $('#cursor');
    var follower = $('#cursorFollower');
    if (cursor && follower && window.matchMedia('(pointer:fine)').matches) {
      document.addEventListener('mousemove', function (e) {
        cursor.style.transform = 'translate(' + (e.clientX - 4) + 'px,' + (e.clientY - 4) + 'px)';
        follower.style.transform = 'translate(' + (e.clientX - 20) + 'px,' + (e.clientY - 20) + 'px)';
      });
    }
    /* audio toggle */
    var audio = $('#cosmicAudio');
    var btn = $('#toggleMusic');
    if (audio && btn) {
      var on = false;
      btn.addEventListener('click', function () {
        if (on) {
          audio.pause();
          btn.innerHTML = '<i class="fas fa-music mr-2"></i>Cosmic Sound';
        } else {
          var src = audio.querySelector('source');
          if (src && !audio.getAttribute('data-loaded')) { audio.setAttribute('data-loaded', '1'); audio.load(); }
          var p = audio.play(); if (p && p.catch) p.catch(function () {});
          btn.innerHTML = '<i class="fas fa-pause mr-2"></i>Pause Sound';
        }
        on = !on;
      });
    }
    initCosmicDecor();
    /* hero buttons */
    window.scrollToProjects = function () {
      var target = $('#projects');
      if (typeof gsap !== 'undefined' && gsap.plugins && gsap.plugins.scrollTo) {
        gsap.to(window, { duration: 2, scrollTo: '#projects', ease: 'power2.inOut' });
      } else if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    };
    window.startImmersion = function () {
      var pre = $('#quantum-preloader');
      if (pre) {
        pre.style.opacity = '1'; pre.style.visibility = 'visible';
        setTimeout(function () {
          pre.style.opacity = '0'; pre.style.visibility = 'hidden';
          window.scrollToProjects();
        }, 1200);
      } else { window.scrollToProjects(); }
    };
  }

  function initCosmicDecor() {
    var host = $('.infinite-scroll');
    if (host && !host.__particles) {
      host.__particles = true;
      for (var i = 0; i < 30; i++) {
        var pt = document.createElement('div');
        pt.className = 'cosmic-particle';
        pt.style.left = Math.random() * 100 + 'vw';
        pt.style.top = Math.random() * 100 + 'vh';
        pt.style.animationDelay = (Math.random() * 6) + 's';
        var size = (Math.random() * 4 + 2) + 'px';
        pt.style.width = size; pt.style.height = size;
        host.appendChild(pt);
      }
    }
    if (typeof gsap !== 'undefined' && typeof ScrollTrigger !== 'undefined') {
      gsap.registerPlugin(ScrollTrigger);
      gsap.to('.cosmic-bg', {
        yPercent: -50, ease: 'none',
        scrollTrigger: { trigger: '.infinite-scroll', start: 'top bottom', end: 'bottom top', scrub: true }
      });
    }
  }

  function initForms() {
    function ajaxify(form, statusEl, okMsg) {
      if (!form || form.__bound) return;
      form.__bound = true;
      form.addEventListener('submit', function (e) {
        e.preventDefault();
        if (statusEl) { statusEl.textContent = 'Sending\u2026'; statusEl.style.color = ''; }
        fetch(form.action, { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } })
          .then(function (res) {
            if (res.ok) {
              if (statusEl) { statusEl.textContent = okMsg; statusEl.style.color = '#16a34a'; }
              form.reset();
            } else {
              if (statusEl) { statusEl.textContent = 'Oops! There was a problem submitting your form.'; statusEl.style.color = '#dc2626'; }
            }
          })
          .catch(function () {
            if (statusEl) { statusEl.textContent = 'Network error. Please try again.'; statusEl.style.color = '#dc2626'; }
          });
      });
    }
    ajaxify($('#contact-form'), $('#form-status'), (content.pages.home.contactSection.form || {}).successMessage || 'Thank you! Your message has been sent.');
    ajaxify($('#newsletter-form'), $('#form-message'), (content.pages.home.footer.newsletter || {}).successMessage || 'Subscribed!');
    ajaxify($('#review-form'), $('#form-status'), 'Thank you! Your review has been submitted.');
  }

  function initTawk() {
    var integ = content.site.integrations;
    if (!integ.tawkToEnabled || !integ.tawkToId || PREVIEW) return;
    var load = function () {
      if (window.__tawkLoaded) return;
      window.__tawkLoaded = true;
      window.Tawk_API = window.Tawk_API || {};
      window.Tawk_LoadStart = new Date();
      var s1 = document.createElement('script');
      s1.async = true;
      s1.src = 'https://embed.tawk.to/' + integ.tawkToId;
      s1.charset = 'UTF-8';
      s1.setAttribute('crossorigin', '*');
      document.head.appendChild(s1);
    };
    /* defer the chat widget: after first interaction or 6s idle */
    ['scroll', 'pointerdown', 'keydown', 'touchstart'].forEach(function (ev) {
      window.addEventListener(ev, load, { once: true, passive: true });
    });
    setTimeout(load, 6000);
  }

  function hidePreloader() {
    var pre = $('#preloader') || $('#quantum-preloader');
    if (!pre) return;
    pre.style.opacity = '0';
    pre.style.visibility = 'hidden';
    setTimeout(function () { pre.style.display = 'none'; }, 900);
  }

  /* ------------------------------------------------------------------ */
  /* Render dispatcher                                                   */
  /* ------------------------------------------------------------------ */

  function render() {
    if (!content) return;
    try {
      applySeo();
      if (PAGE === 'home') { renderHome(); }
      else if (PAGE === 'showcase' || PAGE === 'showcase2') { renderShowcase(); }
      else if (PAGE === 'reviews') { renderReviews(); }
      initForms();
    } catch (err) {
      console.error('[ElitexCMS] render error:', err);
    }
    hidePreloader();
  }

  /* ------------------------------------------------------------------ */
  /* Live preview bridge                                                 */
  /* ------------------------------------------------------------------ */

  function initPreviewBridge() {
    var bar = document.createElement('div');
    bar.className = 'cms-preview-bar';
    bar.innerHTML = '<span class="dot"></span> LIVE PREVIEW \u2014 draft content';
    document.body.appendChild(bar);

    window.addEventListener('message', function (e) {
      var msg = e.data;
      if (!msg || msg.type !== 'cms:content' || !msg.content) return;
      content = msg.content;
      render();
    });
    /* draft edited in another tab of the same browser */
    window.addEventListener('storage', function (e) {
      if (e.key === DRAFT_KEY && e.newValue) {
        try { content = JSON.parse(e.newValue); render(); } catch (err) {}
      }
    });
    if (window.parent !== window) {
      window.parent.postMessage({ type: 'cms:ready', page: PAGE }, '*');
    }
  }

  /* ------------------------------------------------------------------ */
  /* Boot                                                                */
  /* ------------------------------------------------------------------ */

  function boot() {
    if (PREVIEW) {
      initPreviewBridge();
      try {
        var draft = localStorage.getItem(DRAFT_KEY);
        if (draft) content = JSON.parse(draft);
      } catch (e) {}
    }

    var chrome = function () {
      if (PAGE === 'home') initHomeChrome();
      else if (PAGE === 'showcase' || PAGE === 'showcase2') initShowcaseChrome();
      else if (PAGE === 'reviews') initCosmicDecor();
    };

    fetch('content/content.json', { cache: 'no-cache' })
      .then(function (r) { return r.json(); })
      .then(function (json) {
        if (!content) content = json; /* preview draft wins */
        render();
        chrome();
        initTawk();
      })
      .catch(function (err) {
        console.error('[ElitexCMS] failed to load content.json:', err);
        if (content) { render(); chrome(); } else { hidePreloader(); }
      });

    /* safety: never trap users behind the preloader */
    setTimeout(hidePreloader, 4000);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
